title: Arpit Tripathi
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# url: "http://blogs.arpit04tripathi.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/notebook" # the subpath of your site, e.g. /blog

# theme variables
iconURL: "/assets/logo/logo-arpit04tripathi.jpeg"

# custom variables
cdn: https://image.shutterstock.com/image-photo

# Setting theme
# theme: jekyll-theme-leaf                      # For supported theme
remote_theme: SupunKavinda/jekyll-theme-leaf    # For custom themes

# social icons
twitter_username: jekyllrb
github_username:  blogs-arpit04tripathi

# Build settings
plugins:
  - jekyll-feed
collections:
  src:
    output: true
